/*
 * RTOS_Config.h
 *
 *  Created on: Mar 19, 2023
 *      Author: Ali Emad Ali
 */

#ifndef INCLUDE_MY_RTOS_RTOS_CONFIG_H_
#define INCLUDE_MY_RTOS_RTOS_CONFIG_H_


#define RTOS_MAX_NUMBER_OF_PRIORITY_LEVELS				10
#define NULL_PRI		RTOS_MAX_NUMBER_OF_PRIORITY_LEVELS

#define RTOS_MAX_NUMBER_OF_TASKS_PER_PRIORITY_LEVEL		3

#define RTOS_MAX_NUMBER_OF_TCBS		\
	(RTOS_MAX_NUMBER_OF_PRIORITY_LEVELS * RTOS_MAX_NUMBER_OF_TASKS_PER_PRIORITY_LEVEL)

#define RTOS_TICK_MS									1

#endif /* INCLUDE_MY_RTOS_RTOS_CONFIG_H_ */
